### ISSUE TITLE
Anchor button doesnt work

### ISSUE THREAD

**Issue by raymondgeerts** [ryancramerdesign/InputfieldCKEditor#8]
When pressing the anchor button it triggers a transparent layer but further nothing happens. No javascript errors what so ever. A page reload is needed to be able to continue.

**Comment by ryancramerdesign** [comment]
Confirmed. I'm seeing the same thing here. It was working before, so I'm wondering if it stopped working after upgrading to CKEditor 4.1.2. Too bad there aren't any indicators here (JS errors, etc.). But looks like a new version of CKEditor is available, so I'm going to go ahead and upgrade to that and see if that resolves it.

**Comment by ryancramerdesign** [comment]
Upgraded to CKEditor 4.2.0, but unfortunately the behavior is the same. I'll keep looking into it, but if I can't find how to resolve this one I'll probably have to remove the Anchor button from the default toolbar.

**Comment by ryancramerdesign** [comment]
The issue with the Anchor button not working is actually a result of "Link" being in the list of "Removed Plugins" in the field settings. Apparently Anchor requires the Link plugin. So to fix this, just remove "Link" from the Removed Plugins list in your field settings. I've updated the module settings so that future installs won't have Link in the list of removed plugins. But existing installs will have to update their field settings to remove it.

**Comment by raymondgeerts** [comment]
Thanks Ryan. Indeed now it works fine.
